version: '3'
services:
  web:
    build:
      context: . # current working directory. If nested can specify folder name
      dockerfile: Dockerfile.dev # To specify custom dockerfile  instead of .
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]